FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["HappyHoliday/HappyHoliday.csproj", "HappyHoliday/"]
RUN dotnet restore "HappyHoliday/HappyHoliday.csproj"
COPY . .
WORKDIR "/src/HappyHoliday"
RUN dotnet build "HappyHoliday.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HappyHoliday.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HappyHoliday.dll"]
